def Articles():
	articles = [
		{
			'id' : 1,
			'title' :  'Article One',
			'body' : 'Do dolore sit aliqua officia id irure est et incididunt ut excepteur elit cillum laborum minim eiusmod duis laborum dolor ullamco dolore duis aute do adipisicing nulla adipisicing ut duis ea dolor velit consequat qui deserunt velit in sint est laborum est esse laborum nulla eiusmod in eiusmod irure qui velit sed sit ad ut anim est eiusmod exercitation fugiat in eu sit elit ut voluptate nostrud non est ullamco mollit officia laboris commodo eu proident velit labore et in velit ut ut excepteur labore excepteur excepteur commodo officia non sit sit magna irure cillum adipisicing consectetur exercitation dolor aliqua cillum exercitation officia ullamco occaecat sunt do nisi laboris voluptate in culpa sint duis aute est dolore officia mollit consectetur non sunt laboris deserunt irure ut in in anim dolore et consectetur magna officia est magna in ullamco pariatur dolor occaecat exercitation labore non fugiat enim cillum fugiat commodo dolor ut nulla nostrud dolore ex minim minim minim eiusmod dolore laboris elit consectetur reprehenderit nisi ad cillum non ex amet laborum consequat nulla tempor ut do laboris aliquip aliquip dolor eiusmod quis ex velit mollit culpa aliquip ut occaecat adipisicing id cupidatat duis ea pariatur pariatur esse sint do irure officia id exercitation in labore excepteur non enim culpa dolore laboris excepteur sit quis sit minim officia non amet ut ut culpa adipisicing in laborum duis nostrud sunt nulla dolore ullamco nulla eu ut consectetur do ullamco dolor et occaecat sint sit cillum ut exercitation elit do veniam non deserunt labore dolore fugiat cupidatat sit ea esse excepteur incididunt in dolore nulla consequat cillum deserunt.',
			'author' : 'Riffadi Taufik Hidayah',
			'create_date' : '16-06-2019'
		},
		{
			'id' : 2,
			'title' :  'Article Two',
			'body' : 'Do dolore sit aliqua officia id irure est et incididunt ut excepteur elit cillum laborum minim eiusmod duis laborum dolor ullamco dolore duis aute do adipisicing nulla adipisicing ut duis ea dolor velit consequat qui deserunt velit in sint est laborum est esse laborum nulla eiusmod in eiusmod irure qui velit sed sit ad ut anim est eiusmod exercitation fugiat in eu sit elit ut voluptate nostrud non est ullamco mollit officia laboris commodo eu proident velit labore et in velit ut ut excepteur labore excepteur excepteur commodo officia non sit sit magna irure cillum adipisicing consectetur exercitation dolor aliqua cillum exercitation officia ullamco occaecat sunt do nisi laboris voluptate in culpa sint duis aute est dolore officia mollit consectetur non sunt laboris deserunt irure ut in in anim dolore et consectetur magna officia est magna in ullamco pariatur dolor occaecat exercitation labore non fugiat enim cillum fugiat commodo dolor ut nulla nostrud dolore ex minim minim minim eiusmod dolore laboris elit consectetur reprehenderit nisi ad cillum non ex amet laborum consequat nulla tempor ut do laboris aliquip aliquip dolor eiusmod quis ex velit mollit culpa aliquip ut occaecat adipisicing id cupidatat duis ea pariatur pariatur esse sint do irure officia id exercitation in labore excepteur non enim culpa dolore laboris excepteur sit quis sit minim officia non amet ut ut culpa adipisicing in laborum duis nostrud sunt nulla dolore ullamco nulla eu ut consectetur do ullamco dolor et occaecat sint sit cillum ut exercitation elit do veniam non deserunt labore dolore fugiat cupidatat sit ea esse excepteur incididunt in dolore nulla consequat cillum deserunt.',
			'author' : 'Riffadi Taufik Hidayah',
			'create_date' : '16-06-2019'
		},
		{
			'id' : 3,
			'title' :  'Article Three',
			'body' : 'Do dolore sit aliqua officia id irure est et incididunt ut excepteur elit cillum laborum minim eiusmod duis laborum dolor ullamco dolore duis aute do adipisicing nulla adipisicing ut duis ea dolor velit consequat qui deserunt velit in sint est laborum est esse laborum nulla eiusmod in eiusmod irure qui velit sed sit ad ut anim est eiusmod exercitation fugiat in eu sit elit ut voluptate nostrud non est ullamco mollit officia laboris commodo eu proident velit labore et in velit ut ut excepteur labore excepteur excepteur commodo officia non sit sit magna irure cillum adipisicing consectetur exercitation dolor aliqua cillum exercitation officia ullamco occaecat sunt do nisi laboris voluptate in culpa sint duis aute est dolore officia mollit consectetur non sunt laboris deserunt irure ut in in anim dolore et consectetur magna officia est magna in ullamco pariatur dolor occaecat exercitation labore non fugiat enim cillum fugiat commodo dolor ut nulla nostrud dolore ex minim minim minim eiusmod dolore laboris elit consectetur reprehenderit nisi ad cillum non ex amet laborum consequat nulla tempor ut do laboris aliquip aliquip dolor eiusmod quis ex velit mollit culpa aliquip ut occaecat adipisicing id cupidatat duis ea pariatur pariatur esse sint do irure officia id exercitation in labore excepteur non enim culpa dolore laboris excepteur sit quis sit minim officia non amet ut ut culpa adipisicing in laborum duis nostrud sunt nulla dolore ullamco nulla eu ut consectetur do ullamco dolor et occaecat sint sit cillum ut exercitation elit do veniam non deserunt labore dolore fugiat cupidatat sit ea esse excepteur incididunt in dolore nulla consequat cillum deserunt.',
			'author' : 'Riffadi Taufik Hidayah',
			'create_date' : '16-06-2019'
		}
	]
	